export const docsLinks = [
  { href: "/docs", label: "Overview", description: "What XS is and how to navigate the docs" },
  { href: "/docs/getting-started", label: "Getting started", description: "Install XS and write your first program" },
  { href: "/docs/types", label: "Type system", description: "Gradual typing, annotations, and inference" },
  { href: "/docs/functions", label: "Functions", description: "Closures, generators, default args, and overloading" },
  { href: "/docs/pattern-matching", label: "Pattern matching", description: "Destructuring, guards, ranges, and exhaustiveness" },
  { href: "/docs/effects", label: "Effects", description: "Algebraic effects for errors, async, and more" },
  { href: "/docs/structs-and-traits", label: "Structs and traits", description: "Custom types, traits, and operator overloading" },
  { href: "/docs/literals", label: "Universal literals", description: "Tagged literals for dates, URLs, colors, and units" },
  { href: "/docs/temporal", label: "Temporal primitives", description: "Built-in time, duration, and scheduling" },
  { href: "/docs/concurrency", label: "Concurrency", description: "Spawn, channels, actors, nurseries, async/await" },
  { href: "/docs/reactive", label: "Reactive and contracts", description: "Reactive bindings, gradual contracts, and adapt blocks" },
  { href: "/docs/interop", label: "Interop", description: "Inline C, FFI, and calling into JS or WASM" },
  { href: "/docs/browser-sdk", label: "Browser SDK", description: "Run XS in any webpage with one script tag" },
  { href: "/docs/reactive", label: "Reactive primitives", description: "Reactive bindings, contracts, and adapt blocks" },
  { href: "/docs/packages", label: "Packages", description: "Package registry and the xsi installer" },
  { href: "/docs/tooling", label: "Tooling", description: "LSP, debugger, formatter, test runner, and plugins" },
];
